[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "docs"
version = "1.0.0"
description = "This is the package installer for docs"
authors = ["Mozilla"]

[tool.poetry.dependencies]
python = "^3.7"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
mkdocs = { version = "1.0.4", optional = true }
mkdocs-material = { version = "4.6.3", optional = true }
mdx_truly_sane_lists = { version = "1.2", optional = true }

[tool.poetry.extras]
docs = ["mkdocs", "mkdocs-material", "mdx_truly_sane_lists"]


[tool.poetry.dev-dependencies]
betamax = "^0.8.1"
betamax-serializers = "^0.2.1"
flake8 = "^3.8.3"
pytest = "^5.4.3"
pytest-django = "^3.9.0"
pytest-freezegun = "^0.4.1"
pytest-testmon = "^1.0.2"
pytest-watch = "^4.2.0"
shellcheck-py = "^0.7.1"

[tool.black]
line-length = 100
target-version = ['py37']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    treeherder/model/migrations
  | treeherder/perf/migrations
  | treeherder/changelog/migrations
)/
'''