[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "docs"
version = "1.0.0"
description = "This is the package installer for docs"
authors = ["Mozilla"]

[tool.poetry.dependencies]
python = "^3.8"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
mkdocs = { version = "1.0.4", optional = true }
mkdocs-material = { version = "4.6.3", optional = true }
mdx_truly_sane_lists = { version = "1.2", optional = true }
gunicorn = "20.0.4"
# Used by Whitenoise to provide Brotli-compressed versions of static files.
whitenoise = {version = "5.1.0", extras = ["brotli"]}
Django = "3.0.8"
# 4.4.2 required to pass test_retryable_task_throws_retry, celery needed for data ingestion
celery = "4.4.2"
simplejson = "3.17.0"
newrelic = "5.2.1.129"
mysqlclient = "2.0.1"
jsonschema = "3.2.0"
# Imported as rest_framework
djangorestframework = "3.11.0"
# Listed as 3rd party app on settings.py
django-cors-headers = "3.4.0"
mozlog = "6.0"
# `coreapi` must be installed for schema support.
coreapi = "2.3.3"
# Imported as yaml
pyyaml = "5.3.1"
# Imported as environ
django-environ = "0.4.5"
django-filter = "^2.3.0"
django-redis = "^4.12.1"
taskcluster = "30.1.1"
aiohttp = "^3.6.2"  # Peer dependency of taskcluster
async-timeout = "^3.0.1"  # Peer dependency of taskcluster
# from typing import ...
typing = "3.7.4.3"
python-jose = {version = "3.1.0", extras = ["pycryptodome"]}
furl = "2.1.0"
first = "2.0.2"
json-e = "3.0.2"
# Imported as cache_memoize
django-cache-memoize = "0.1.7"
# The following three are required for extraction to BigQuery
jx-bigquery = "^3.85.20198"
jx-mysql = "^3.85.20198"
mo-testing = "^3.78.20194"
# Required for Push Health
mozci = "^1.6.5"

[tool.poetry.extras]
docs = ["mkdocs", "mkdocs-material", "mdx_truly_sane_lists"]


[tool.poetry.dev-dependencies]
betamax = "^0.8.1"
betamax-serializers = "^0.2.1"
flake8 = "^3.8.3"
pytest = "^5.4.3"
pytest-django = "^3.9.0"
pytest-freezegun = "^0.4.1"
pytest-testmon = "^1.0.2"
pytest-watch = "^4.2.0"
shellcheck-py = "^0.7.1"
poetry = "^1.0.10"
black = "^19.10b0"
responses = "^0.10.15"

[tool.black]
line-length = 100
target-version = ['py37']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    treeherder/model/migrations
  | treeherder/perf/migrations
  | treeherder/changelog/migrations
)/
'''